// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivtbqcqvbovbtwbgzhmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2dGJxY3F2Ym92YnR3Ymd6aG16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MTA4NjEsImV4cCI6MjA3MTM4Njg2MX0.F9zGfW-l1lUPVBpLwjQggzLPvB9EtlhE_Njw2uYYZdA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});